# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc532b26535a0e73c18d89943f9d983ca0ceb8818e4fd810bcc22bc15d1651a4a24297c0fdf7ed9fdf30a99c2db57cf5c96830966369fa9cab3103dc68560a5b

test:
  secret_key_base: afcff43c76fc0f626d139684da9f0c64f58122b343b55c65c39493de8fd05b40281f668ef64b275c69a9fcf17363cda72fd1ecaa2c13f5a99bd1cacbcfb3ce0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
